# Generated by Django 5.2.7 on 2026-01-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companyinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='map_url',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='google_map_embed',
            field=models.TextField(blank=True, help_text='Paste Google Maps iframe embed code', null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
