# Generated by Django 5.2.7 on 2026-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_companyinfo_map_url_companyinfo_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('discount_percentage', models.PositiveIntegerField(default=10)),
                ('button_text', models.CharField(default='Book Now', max_length=50)),
                ('button_link', models.CharField(default='/resorts/', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
