# Generated by Django 5.2.7 on 2026-01-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_rooms', models.IntegerField()),
                ('image', models.ImageField(upload_to='resorts/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
